DELETE
FROM EMPLOYEETITLES;

DELETE
FROM JOBTITLES;

DELETE
FROM EMAILS;

DELETE
FROM EMPLOYEES;

INSERT INTO EMPLOYEES (EMPLOYEEID, NAME, SALARY, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE)
    VALUES (1, 'CINNAMON', 80000.00, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
           (2, 'BARNBARN', 80000.00, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
           (3, 'JOHN', 75000.00, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);

INSERT INTO EMAILS (EMAILID, EMAIL, EMPLOYEEID, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE)
    VALUES (1, 'hops@local.com', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
           (2, 'bunny@hoppin.local', 1, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
           (3, 'barnbarn@local.com', 2, 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);

INSERT INTO JOBTITLES (JOBTITLEID, TITLE, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE)
    VALUES (1, 'Big Boss', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
           (2, 'Wizard', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);

INSERT INTO EMPLOYEETITLES (EMPLOYEEID, JOBTITLEID, MANAGER, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE)
    VALUES (1, 1, 'MOJO', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
           (1, 2, 'STUBS', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP),
           (2, 2, 'MOJO', 'SYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', CURRENT_TIMESTAMP);

/*
Must tell hibernate of the id numbers already used.
The number after with must be greater that the highest number id assigned.
 */
alter sequence hibernate_sequence restart with 15;